// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentAck.proto

#ifndef PROTOBUF_PaymentAck_2eproto__INCLUDED
#define PROTOBUF_PaymentAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Payment.pb.h"
// @@protoc_insertion_point(includes)
class PaymentAck;
class PaymentAckDefaultTypeInternal;
extern PaymentAckDefaultTypeInternal _PaymentAck_default_instance_;

namespace protobuf_PaymentAck_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_PaymentAck_2eproto

// ===================================================================

class PaymentAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PaymentAck) */ {
 public:
  PaymentAck();
  virtual ~PaymentAck();

  PaymentAck(const PaymentAck& from);

  inline PaymentAck& operator=(const PaymentAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PaymentAck(PaymentAck&& from) noexcept
    : PaymentAck() {
    *this = ::std::move(from);
  }

  inline PaymentAck& operator=(PaymentAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaymentAck& default_instance();

  static inline const PaymentAck* internal_default_instance() {
    return reinterpret_cast<const PaymentAck*>(
               &_PaymentAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PaymentAck* other);
  friend void swap(PaymentAck& a, PaymentAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PaymentAck* New() const PROTOBUF_FINAL { return New(NULL); }

  PaymentAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaymentAck& from);
  void MergeFrom(const PaymentAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaymentAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string memo = 2;
  bool has_memo() const;
  void clear_memo();
  static const int kMemoFieldNumber = 2;
  const ::std::string& memo() const;
  void set_memo(const ::std::string& value);
  #if LANG_CXX11
  void set_memo(::std::string&& value);
  #endif
  void set_memo(const char* value);
  void set_memo(const char* value, size_t size);
  ::std::string* mutable_memo();
  ::std::string* release_memo();
  void set_allocated_memo(::std::string* memo);

  // required .Payment payment = 1;
  bool has_payment() const;
  void clear_payment();
  static const int kPaymentFieldNumber = 1;
  const ::Payment& payment() const;
  ::Payment* mutable_payment();
  ::Payment* release_payment();
  void set_allocated_payment(::Payment* payment);

  // @@protoc_insertion_point(class_scope:PaymentAck)
 private:
  void set_has_payment();
  void clear_has_payment();
  void set_has_memo();
  void clear_has_memo();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr memo_;
  ::Payment* payment_;
  friend struct protobuf_PaymentAck_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PaymentAck

// required .Payment payment = 1;
inline bool PaymentAck::has_payment() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PaymentAck::set_has_payment() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PaymentAck::clear_has_payment() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PaymentAck::clear_payment() {
  if (payment_ != NULL) payment_->::Payment::Clear();
  clear_has_payment();
}
inline const ::Payment& PaymentAck::payment() const {
  const ::Payment* p = payment_;
  // @@protoc_insertion_point(field_get:PaymentAck.payment)
  return p != NULL ? *p : *reinterpret_cast<const ::Payment*>(
      &::_Payment_default_instance_);
}
inline ::Payment* PaymentAck::mutable_payment() {
  set_has_payment();
  if (payment_ == NULL) {
    payment_ = new ::Payment;
  }
  // @@protoc_insertion_point(field_mutable:PaymentAck.payment)
  return payment_;
}
inline ::Payment* PaymentAck::release_payment() {
  // @@protoc_insertion_point(field_release:PaymentAck.payment)
  clear_has_payment();
  ::Payment* temp = payment_;
  payment_ = NULL;
  return temp;
}
inline void PaymentAck::set_allocated_payment(::Payment* payment) {
  delete payment_;
  payment_ = payment;
  if (payment) {
    set_has_payment();
  } else {
    clear_has_payment();
  }
  // @@protoc_insertion_point(field_set_allocated:PaymentAck.payment)
}

// optional string memo = 2;
inline bool PaymentAck::has_memo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PaymentAck::set_has_memo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PaymentAck::clear_has_memo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PaymentAck::clear_memo() {
  memo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_memo();
}
inline const ::std::string& PaymentAck::memo() const {
  // @@protoc_insertion_point(field_get:PaymentAck.memo)
  return memo_.GetNoArena();
}
inline void PaymentAck::set_memo(const ::std::string& value) {
  set_has_memo();
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PaymentAck.memo)
}
#if LANG_CXX11
inline void PaymentAck::set_memo(::std::string&& value) {
  set_has_memo();
  memo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PaymentAck.memo)
}
#endif
inline void PaymentAck::set_memo(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_memo();
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PaymentAck.memo)
}
inline void PaymentAck::set_memo(const char* value, size_t size) {
  set_has_memo();
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PaymentAck.memo)
}
inline ::std::string* PaymentAck::mutable_memo() {
  set_has_memo();
  // @@protoc_insertion_point(field_mutable:PaymentAck.memo)
  return memo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentAck::release_memo() {
  // @@protoc_insertion_point(field_release:PaymentAck.memo)
  clear_has_memo();
  return memo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentAck::set_allocated_memo(::std::string* memo) {
  if (memo != NULL) {
    set_has_memo();
  } else {
    clear_has_memo();
  }
  memo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), memo);
  // @@protoc_insertion_point(field_set_allocated:PaymentAck.memo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PaymentAck_2eproto__INCLUDED
