// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentDetailsV3.proto

#ifndef PROTOBUF_PaymentDetailsV3_2eproto__INCLUDED
#define PROTOBUF_PaymentDetailsV3_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "OutputV3.pb.h"
// @@protoc_insertion_point(includes)
namespace com {
namespace bitcoin {
namespace proto3 {
class PaymentDetails;
class PaymentDetailsDefaultTypeInternal;
extern PaymentDetailsDefaultTypeInternal _PaymentDetails_default_instance_;
}  // namespace proto3
}  // namespace bitcoin
}  // namespace com

namespace com {
namespace bitcoin {
namespace proto3 {

namespace protobuf_PaymentDetailsV3_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_PaymentDetailsV3_2eproto

// ===================================================================

class PaymentDetails : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.bitcoin.proto3.PaymentDetails) */ {
 public:
  PaymentDetails();
  virtual ~PaymentDetails();

  PaymentDetails(const PaymentDetails& from);

  inline PaymentDetails& operator=(const PaymentDetails& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PaymentDetails(PaymentDetails&& from) noexcept
    : PaymentDetails() {
    *this = ::std::move(from);
  }

  inline PaymentDetails& operator=(PaymentDetails&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PaymentDetails& default_instance();

  static inline const PaymentDetails* internal_default_instance() {
    return reinterpret_cast<const PaymentDetails*>(
               &_PaymentDetails_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PaymentDetails* other);
  friend void swap(PaymentDetails& a, PaymentDetails& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PaymentDetails* New() const PROTOBUF_FINAL { return New(NULL); }

  PaymentDetails* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaymentDetails& from);
  void MergeFrom(const PaymentDetails& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaymentDetails* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.bitcoin.proto3.Output outputs = 2;
  int outputs_size() const;
  void clear_outputs();
  static const int kOutputsFieldNumber = 2;
  const ::com::bitcoin::proto3::Output& outputs(int index) const;
  ::com::bitcoin::proto3::Output* mutable_outputs(int index);
  ::com::bitcoin::proto3::Output* add_outputs();
  ::google::protobuf::RepeatedPtrField< ::com::bitcoin::proto3::Output >*
      mutable_outputs();
  const ::google::protobuf::RepeatedPtrField< ::com::bitcoin::proto3::Output >&
      outputs() const;

  // string network = 1;
  void clear_network();
  static const int kNetworkFieldNumber = 1;
  const ::std::string& network() const;
  void set_network(const ::std::string& value);
  #if LANG_CXX11
  void set_network(::std::string&& value);
  #endif
  void set_network(const char* value);
  void set_network(const char* value, size_t size);
  ::std::string* mutable_network();
  ::std::string* release_network();
  void set_allocated_network(::std::string* network);

  // string memo = 5;
  void clear_memo();
  static const int kMemoFieldNumber = 5;
  const ::std::string& memo() const;
  void set_memo(const ::std::string& value);
  #if LANG_CXX11
  void set_memo(::std::string&& value);
  #endif
  void set_memo(const char* value);
  void set_memo(const char* value, size_t size);
  ::std::string* mutable_memo();
  ::std::string* release_memo();
  void set_allocated_memo(::std::string* memo);

  // string payment_url = 6;
  void clear_payment_url();
  static const int kPaymentUrlFieldNumber = 6;
  const ::std::string& payment_url() const;
  void set_payment_url(const ::std::string& value);
  #if LANG_CXX11
  void set_payment_url(::std::string&& value);
  #endif
  void set_payment_url(const char* value);
  void set_payment_url(const char* value, size_t size);
  ::std::string* mutable_payment_url();
  ::std::string* release_payment_url();
  void set_allocated_payment_url(::std::string* payment_url);

  // bytes merchant_data = 7;
  void clear_merchant_data();
  static const int kMerchantDataFieldNumber = 7;
  const ::std::string& merchant_data() const;
  void set_merchant_data(const ::std::string& value);
  #if LANG_CXX11
  void set_merchant_data(::std::string&& value);
  #endif
  void set_merchant_data(const char* value);
  void set_merchant_data(const void* value, size_t size);
  ::std::string* mutable_merchant_data();
  ::std::string* release_merchant_data();
  void set_allocated_merchant_data(::std::string* merchant_data);

  // string someNewField = 9;
  void clear_somenewfield();
  static const int kSomeNewFieldFieldNumber = 9;
  const ::std::string& somenewfield() const;
  void set_somenewfield(const ::std::string& value);
  #if LANG_CXX11
  void set_somenewfield(::std::string&& value);
  #endif
  void set_somenewfield(const char* value);
  void set_somenewfield(const char* value, size_t size);
  ::std::string* mutable_somenewfield();
  ::std::string* release_somenewfield();
  void set_allocated_somenewfield(::std::string* somenewfield);

  // uint64 time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // uint64 expires = 4;
  void clear_expires();
  static const int kExpiresFieldNumber = 4;
  ::google::protobuf::uint64 expires() const;
  void set_expires(::google::protobuf::uint64 value);

  // int32 someNewInt = 10;
  void clear_somenewint();
  static const int kSomeNewIntFieldNumber = 10;
  ::google::protobuf::int32 somenewint() const;
  void set_somenewint(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.bitcoin.proto3.PaymentDetails)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::bitcoin::proto3::Output > outputs_;
  ::google::protobuf::internal::ArenaStringPtr network_;
  ::google::protobuf::internal::ArenaStringPtr memo_;
  ::google::protobuf::internal::ArenaStringPtr payment_url_;
  ::google::protobuf::internal::ArenaStringPtr merchant_data_;
  ::google::protobuf::internal::ArenaStringPtr somenewfield_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::uint64 expires_;
  ::google::protobuf::int32 somenewint_;
  mutable int _cached_size_;
  friend struct protobuf_PaymentDetailsV3_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PaymentDetails

// string network = 1;
inline void PaymentDetails::clear_network() {
  network_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentDetails::network() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.network)
  return network_.GetNoArena();
}
inline void PaymentDetails::set_network(const ::std::string& value) {
  
  network_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.network)
}
#if LANG_CXX11
inline void PaymentDetails::set_network(::std::string&& value) {
  
  network_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.bitcoin.proto3.PaymentDetails.network)
}
#endif
inline void PaymentDetails::set_network(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  network_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.bitcoin.proto3.PaymentDetails.network)
}
inline void PaymentDetails::set_network(const char* value, size_t size) {
  
  network_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.bitcoin.proto3.PaymentDetails.network)
}
inline ::std::string* PaymentDetails::mutable_network() {
  
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.network)
  return network_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentDetails::release_network() {
  // @@protoc_insertion_point(field_release:com.bitcoin.proto3.PaymentDetails.network)
  
  return network_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentDetails::set_allocated_network(::std::string* network) {
  if (network != NULL) {
    
  } else {
    
  }
  network_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), network);
  // @@protoc_insertion_point(field_set_allocated:com.bitcoin.proto3.PaymentDetails.network)
}

// repeated .com.bitcoin.proto3.Output outputs = 2;
inline int PaymentDetails::outputs_size() const {
  return outputs_.size();
}
inline void PaymentDetails::clear_outputs() {
  outputs_.Clear();
}
inline const ::com::bitcoin::proto3::Output& PaymentDetails::outputs(int index) const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.outputs)
  return outputs_.Get(index);
}
inline ::com::bitcoin::proto3::Output* PaymentDetails::mutable_outputs(int index) {
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.outputs)
  return outputs_.Mutable(index);
}
inline ::com::bitcoin::proto3::Output* PaymentDetails::add_outputs() {
  // @@protoc_insertion_point(field_add:com.bitcoin.proto3.PaymentDetails.outputs)
  return outputs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::com::bitcoin::proto3::Output >*
PaymentDetails::mutable_outputs() {
  // @@protoc_insertion_point(field_mutable_list:com.bitcoin.proto3.PaymentDetails.outputs)
  return &outputs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::com::bitcoin::proto3::Output >&
PaymentDetails::outputs() const {
  // @@protoc_insertion_point(field_list:com.bitcoin.proto3.PaymentDetails.outputs)
  return outputs_;
}

// uint64 time = 3;
inline void PaymentDetails::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PaymentDetails::time() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.time)
  return time_;
}
inline void PaymentDetails::set_time(::google::protobuf::uint64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.time)
}

// uint64 expires = 4;
inline void PaymentDetails::clear_expires() {
  expires_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PaymentDetails::expires() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.expires)
  return expires_;
}
inline void PaymentDetails::set_expires(::google::protobuf::uint64 value) {
  
  expires_ = value;
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.expires)
}

// string memo = 5;
inline void PaymentDetails::clear_memo() {
  memo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentDetails::memo() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.memo)
  return memo_.GetNoArena();
}
inline void PaymentDetails::set_memo(const ::std::string& value) {
  
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.memo)
}
#if LANG_CXX11
inline void PaymentDetails::set_memo(::std::string&& value) {
  
  memo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.bitcoin.proto3.PaymentDetails.memo)
}
#endif
inline void PaymentDetails::set_memo(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.bitcoin.proto3.PaymentDetails.memo)
}
inline void PaymentDetails::set_memo(const char* value, size_t size) {
  
  memo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.bitcoin.proto3.PaymentDetails.memo)
}
inline ::std::string* PaymentDetails::mutable_memo() {
  
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.memo)
  return memo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentDetails::release_memo() {
  // @@protoc_insertion_point(field_release:com.bitcoin.proto3.PaymentDetails.memo)
  
  return memo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentDetails::set_allocated_memo(::std::string* memo) {
  if (memo != NULL) {
    
  } else {
    
  }
  memo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), memo);
  // @@protoc_insertion_point(field_set_allocated:com.bitcoin.proto3.PaymentDetails.memo)
}

// string payment_url = 6;
inline void PaymentDetails::clear_payment_url() {
  payment_url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentDetails::payment_url() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.payment_url)
  return payment_url_.GetNoArena();
}
inline void PaymentDetails::set_payment_url(const ::std::string& value) {
  
  payment_url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.payment_url)
}
#if LANG_CXX11
inline void PaymentDetails::set_payment_url(::std::string&& value) {
  
  payment_url_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.bitcoin.proto3.PaymentDetails.payment_url)
}
#endif
inline void PaymentDetails::set_payment_url(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  payment_url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.bitcoin.proto3.PaymentDetails.payment_url)
}
inline void PaymentDetails::set_payment_url(const char* value, size_t size) {
  
  payment_url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.bitcoin.proto3.PaymentDetails.payment_url)
}
inline ::std::string* PaymentDetails::mutable_payment_url() {
  
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.payment_url)
  return payment_url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentDetails::release_payment_url() {
  // @@protoc_insertion_point(field_release:com.bitcoin.proto3.PaymentDetails.payment_url)
  
  return payment_url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentDetails::set_allocated_payment_url(::std::string* payment_url) {
  if (payment_url != NULL) {
    
  } else {
    
  }
  payment_url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payment_url);
  // @@protoc_insertion_point(field_set_allocated:com.bitcoin.proto3.PaymentDetails.payment_url)
}

// bytes merchant_data = 7;
inline void PaymentDetails::clear_merchant_data() {
  merchant_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentDetails::merchant_data() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.merchant_data)
  return merchant_data_.GetNoArena();
}
inline void PaymentDetails::set_merchant_data(const ::std::string& value) {
  
  merchant_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.merchant_data)
}
#if LANG_CXX11
inline void PaymentDetails::set_merchant_data(::std::string&& value) {
  
  merchant_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.bitcoin.proto3.PaymentDetails.merchant_data)
}
#endif
inline void PaymentDetails::set_merchant_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  merchant_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.bitcoin.proto3.PaymentDetails.merchant_data)
}
inline void PaymentDetails::set_merchant_data(const void* value, size_t size) {
  
  merchant_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.bitcoin.proto3.PaymentDetails.merchant_data)
}
inline ::std::string* PaymentDetails::mutable_merchant_data() {
  
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.merchant_data)
  return merchant_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentDetails::release_merchant_data() {
  // @@protoc_insertion_point(field_release:com.bitcoin.proto3.PaymentDetails.merchant_data)
  
  return merchant_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentDetails::set_allocated_merchant_data(::std::string* merchant_data) {
  if (merchant_data != NULL) {
    
  } else {
    
  }
  merchant_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), merchant_data);
  // @@protoc_insertion_point(field_set_allocated:com.bitcoin.proto3.PaymentDetails.merchant_data)
}

// string someNewField = 9;
inline void PaymentDetails::clear_somenewfield() {
  somenewfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentDetails::somenewfield() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.someNewField)
  return somenewfield_.GetNoArena();
}
inline void PaymentDetails::set_somenewfield(const ::std::string& value) {
  
  somenewfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.someNewField)
}
#if LANG_CXX11
inline void PaymentDetails::set_somenewfield(::std::string&& value) {
  
  somenewfield_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.bitcoin.proto3.PaymentDetails.someNewField)
}
#endif
inline void PaymentDetails::set_somenewfield(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  somenewfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.bitcoin.proto3.PaymentDetails.someNewField)
}
inline void PaymentDetails::set_somenewfield(const char* value, size_t size) {
  
  somenewfield_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.bitcoin.proto3.PaymentDetails.someNewField)
}
inline ::std::string* PaymentDetails::mutable_somenewfield() {
  
  // @@protoc_insertion_point(field_mutable:com.bitcoin.proto3.PaymentDetails.someNewField)
  return somenewfield_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentDetails::release_somenewfield() {
  // @@protoc_insertion_point(field_release:com.bitcoin.proto3.PaymentDetails.someNewField)
  
  return somenewfield_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentDetails::set_allocated_somenewfield(::std::string* somenewfield) {
  if (somenewfield != NULL) {
    
  } else {
    
  }
  somenewfield_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), somenewfield);
  // @@protoc_insertion_point(field_set_allocated:com.bitcoin.proto3.PaymentDetails.someNewField)
}

// int32 someNewInt = 10;
inline void PaymentDetails::clear_somenewint() {
  somenewint_ = 0;
}
inline ::google::protobuf::int32 PaymentDetails::somenewint() const {
  // @@protoc_insertion_point(field_get:com.bitcoin.proto3.PaymentDetails.someNewInt)
  return somenewint_;
}
inline void PaymentDetails::set_somenewint(::google::protobuf::int32 value) {
  
  somenewint_ = value;
  // @@protoc_insertion_point(field_set:com.bitcoin.proto3.PaymentDetails.someNewInt)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto3
}  // namespace bitcoin
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PaymentDetailsV3_2eproto__INCLUDED
